### PR TITLE
Fix fly_camera demos window focus

### LINKED ISSUE #635: Fly Camera centering mouse without window focus
This is occurring on Windows 10, I am not sure about other operating systems.

It seems that the `MouseCenterLockSystem` keeps centering the mouse in the window even if the window no longer has focus.

This can be reproduced with the fly_camera example and moving focus away from the window (e.g. with alt-tab).

### PR DESCRIPTION
**Pull request by MrMinimal**
This PR fixes the fly_camera example, which still centers the mouse, even if window focus is lost.

Fixes #635

---
This change is [Reviewable](https://reviewable.io/reviews/amethyst/amethyst/694)

### CODE REVIEW

File: amethyst_controls/src/bundles.rs [hunk 1]
```diff
@@ -68,6 +68,7 @@ where
             &[],
         );
         builder.add(MouseCenterLockSystem, "mouse_lock", &["free_rotation"]);
+        builder.add(MouseFocusUpdateSystem::new(), "mouse_focus", &["mouse_lock"]);
```
Comment (jojolepro) [inline amethyst_controls/src/bundles.rs]: MouseFocusUpdateSystem should be running after FreeRotationSystem but before MouseCenterLockSystem if you want to prevent a cursor jump on focus gained.

File: amethyst_controls/src/lib.rs [hunk 2]
```diff
@@ -5,14 +5,17 @@ extern crate amethyst_renderer;
...
 mod components;
 mod bundles;
 mod systems;
+mod resources;
 
 pub use self::bundles::FlyControlBundle;
 pub use self::components::FlyControlTag;
-pub use self::systems::{FlyMovementSystem, FreeRotationSystem, MouseCenterLockSystem};
+pub use self::systems::{FlyMovementSystem, FreeRotationSystem, MouseCenterLockSystem, MouseFocusUpdateSystem};
+pub use self::resources::{WindowFocus};
```
Comment (jojolepro) [inline amethyst_controls/src/lib.rs]: New line

Comment (jojolepro) [reply amethyst_controls/src/lib.rs]: Also you don't need braces {}

File: amethyst_controls/src/resources.rs [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+    pub is_focused: bool,
+}
+
+impl WindowFocus {
+    pub fn new() -> WindowFocus {
+        WindowFocus {
+            is_focused: true,
+        }
+    }
+}
```
Comment (jojolepro) [inline amethyst_controls/src/resources.rs]: New line

File: amethyst_controls/src/resources.rs [hunk 4]
```diff
@@ -0,0 +1,12 @@
+#[derive(Default)]
```
Comment (jojolepro) [inline amethyst_controls/src/resources.rs]: I think having a bit of docs could help new users figure out what this is.

File: amethyst_controls/src/systems.rs [hunk 5]
```diff
@@ -149,3 +166,43 @@ impl<'a> System<'a> for MouseCenterLockSystem {
         set_mouse_cursor_none(&mut msg);
     }
 }
+
+// A system which reads Events and saves if a window has lost focus in a WindowFocus resource
```
Comment (jojolepro) [inline amethyst_controls/src/systems.rs]: // = comment
/// = docs

File: amethyst_controls/src/systems.rs [hunk 6]
```diff
@@ -149,3 +166,43 @@ impl<'a> System<'a> for MouseCenterLockSystem {
...
+            }
+        }
+    }
+
+    fn setup(&mut self, res: &mut Resources) {
+        use amethyst_core::specs::prelude::SystemData;
+        Self::SystemData::setup(res);
+        self.event_reader = Some(res.fetch_mut::<EventChannel<Event>>().register_reader());
+    }
+}
```
Comment (jojolepro) [inline amethyst_controls/src/systems.rs]: New line

**Comment by Rhuagh** [comment]
Just fix the nits above, then we can merge this.

**Comment by MrMinimal** [comment]
@Rhuagh I have fixed the mentioned bis and pieces, so from my POV it's ready to merge. If I can do anything else, let me know.

**Comment by torkleyy** [comment]
Yeah everything's fixed, @jojolepro needs to approve.

File: amethyst_controls/src/resources.rs [hunk 7]
```diff
@@ -0,0 +1,14 @@
+/// Struct which holds information about whether the widow is focused.
```
Comment (jojolepro) [inline amethyst_controls/src/resources.rs]: s/widow/window

File: amethyst_controls/src/resources.rs (hunk 4 above)
Comment (jojolepro) [reply amethyst_controls/src/resources.rs]: done

File: amethyst_controls/src/resources.rs (hunk 3 above)
Comment (jojolepro) [reply amethyst_controls/src/resources.rs]: done

File: amethyst_controls/src/systems.rs (hunk 6 above)
Comment (jojolepro) [reply amethyst_controls/src/systems.rs]: done
