### PR TITLE
Bugfix/2108/ui text spaces highlight

### LINKED ISSUE #2108: [BUG] Selecting ui text causes render bug with spaces
## Description

Adding spaces to text and then selecting it causes the text to have rendering issues.

## Reproduction Steps

1. Load ui example
2. Add space to selectable text.
3. Select the text before and after the space.

## What You Expected to Happen

The selected text should all have the same color.

## What Actually Happened

The color of the text is off by the number of spaces selected.

## Screenshots and Logs

image

## Your Environment

1. Operating System: Windows 10
3. Version of Amethyst: Master

### PR DESCRIPTION
**Pull request by azriel91**
## Description

Fixes #2108.

ui_highlight

## Fixes

- Editable text fields now correctly highlight strings containing spaces.

## PR Checklist

By placing an x in the boxes I certify that I have:

- **n/a** Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- **n/a** Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x] Ran `cargo test --all --features "empty"`

### CODE REVIEW

**Comment by azriel91** [comment]
Leaving this here because it was a random snippet that seemed useful at the time.

<details>

<summary>Initial attempt at fixing overlapping glyphs for a grapheme</summary>

```rust
// Correct positions of glyphs
let mut overlap_correction = 0.0;
let mut cached_glyphs = ui_text.cached_glyphs.iter_mut();
ui_text.text.graphemes(true).for_each(|s| {
    s.chars().enumerate().for_each(|(index, c)| {
        if let Some(cached_glyph) = cached_glyphs.next() {
            cached_glyph.x -= overlap_correction;

            if index != 0 {
                overlap_correction += cached_glyph.advance_width;
            }
        }
    });
});

if let Some(bounds) = glyph_brush_ref.glyph_bounds_custom_layout(section, &layout) {
    glyph_brush_ref.queue_pre_positioned(
        non_empty_glyphs,
        bounds,
        f32::from_bits(entity.id()),
    );
}
```

</details>

**Comment by azriel91** [comment]
bors try

File: amethyst_ui/src/glyphs.rs [hunk 1]
```diff
@@ -310,19 +311,54 @@ impl<'a, B: Backend> System<'a> for UiGlyphsSystem<B> {
...
+
+                        let advance_width =
+                            font_asset.glyph(c).scaled(scale).h_metrics().advance_width;
+
+                        let cached_glyph = CachedGlyph {
+                            x,
+                            y,
+                            advance_width,
+                        };
+                        last_cached_glyph = Some(cached_glyph);
```
Comment (TimonPost) [inline amethyst_ui/src/glyphs.rs]: Maybe just do `Some(cached_glyph)` and remove the assignment and the line below.

File: amethyst_ui/src/glyphs.rs [hunk 2]
```diff
@@ -310,19 +311,54 @@ impl<'a, B: Backend> System<'a> for UiGlyphsSystem<B> {
...
+                        last_cached_glyph
+                    } else {
+                        last_cached_glyph = nonempty_cached_glyphs.next();
```
Comment (TimonPost) [inline amethyst_ui/src/glyphs.rs]: Maybe just do nonempty_cached_glyphs.next()` and remove the assignment and the line below.

File: amethyst_ui/src/glyphs.rs (hunk 1 above)
Comment (azriel91) [reply amethyst_ui/src/glyphs.rs]: ah, the assignment is necessary, because `last_cached_glyph` lives beyond the closure, and is used for the whitespace calculation in subsequent iterations (same for next comment).
