### PR TITLE
Changed Panic to return an error type

### LINKED ISSUE #2020: [FEATURE MODIFICATION] amethyst_tiles::Map::to_tile should accept out-of-bounds input.
## Feature

https://docs.amethyst.rs/stable/amethyst_tiles/trait.Map.html#tymethod.to_tile

This returns an `Option<Point3<u32>>`, but does not document when it's `Some(..)` vs `None`. Currently, it's `Some(..)` if the coordinate is within the map or out-of-bounds in a positive direction (on production builds). If it is out of bounds in a positive direction on debug builds, it panics. if it is out of bounds in a negative direction, it returns `None`.

## Change

I think it should return `None` if out of bounds in a positive direction, and the user should choose whether or not to crash.

## Reason

It is difficult to check in advance whether or not the point coordinate is going to be out of bounds -- figuring out where it is on the grid is the purpose of `to_tile` to begin with! So to correctly call this, one must reproduce some of the logic of `to_tile` to do the bounds checks.

## Impact

Improved documentation for to_tile, since it'd be clear and easy to describe when it returns None. Slightly reduced performance on production builds due to the new bounds check.

## Additional Notes

Alternative approaches:

* Always return a `Point3`, but of `i32` and not `u32`, letting the user check the bounds. (Seems more useful in some ways, but inconvenient due to `i32`/`u32` conversions.)
* Remove the debug crash logic so that it never crashes, only returns `None` (out of bounds, negative) or a `Point3<u32>` (that may or may not be out of bounds, positive). (Slightly weird API, but still useful. Same performance as current approach, just removes the debug-only panic logic.)

IMO any of the above would be easier to use and more helpful than the current API.

* Finally, one could embrace crashing: always return a `Point3<u32>`, and panic if out of bounds. (Same performance impact, but seems less useful.)

For now I've solved this by not clicking out-of-bounds in my toy game. ;)  But I'd like a better solution going forward. If you agree with this approach, or one of the alternatives above, feel free to assign this issue to me and I can write the PR.

### PR DESCRIPTION
**Pull request by mrhatman**
## Description

Resolves #2020 

by returning an error type rather than panic!() .

## Addition

- The error type TileOutOfBoundsError.

## Modification

- to_tile now returns Result<Point<u32>,TileOutOfBoundsError> 
## PR Checklist

By placing an x in the boxes I certify that I have:

- [ ] Updated the content of the book if this PR would make the book outdated.
- [x] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [x] Ran `cargo +stable fmt --all`
- [x] Ran `cargo clippy --all --features "empty"`
- [x ] Ran `cargo test --all --features "empty"`

### CODE REVIEW

File: amethyst_tiles/src/error.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
+//! Renderer error types.
+
+use amethyst_core::math::{Point3, Vector3};
+
+use err_derive::Error;
+
+/// Tile is out of bounds.
+#[derive(Debug, Error)]
+#[error(
+    display = "Requested coordinate is outside map dimensions: '{:?}', max dimensions=:{:?}",
```
Comment (azriel91) [inline amethyst_tiles/src/error.rs]: Curious, is the `=:{:?}` a convention somewhere? (because earlier you've got single quotes)
Oh ya, if you're changing it, I tend to go with backticks surrounding the debugged item -- copying how Rust does it

File: amethyst_tiles/Cargo.toml [hunk 2]
```diff
@@ -33,6 +33,7 @@ lazy_static = "1.3"
 rayon = "1.0.2"
 bitintr = "0.3"
 glsl-layout = "0.3"
+err-derive = "0.1"
```
Comment (azriel91) [inline amethyst_tiles/Cargo.toml]: Should we use 0.2? (the readme on `err-derive` does point to 0.1, but I think that's just forgotten to be updated)

File: amethyst_tiles/src/map.rs [hunk 3]
```diff
@@ -340,22 +326,26 @@ fn to_tile(
...
-    if inverse.z < 0.0 {
-        return None;
+    if inverse.x < 0.0
+        || inverse.x as u32 > max_dimensions.x
+        || inverse.y < 0.0
+        || inverse.y as u32 > max_dimensions.y
+        || inverse.z < 0.0
+        || inverse.z as u32 > max_dimensions.z
+    {
+        let point_dimensions = Point3::new(inverse.x as i32, inverse.y as i32, inverse.z as i32);
```
Comment (azriel91) [inline amethyst_tiles/src/map.rs]: Think these should be `as u32`

**Comment by azriel91** [comment]
(restarted windows build agent)

**Comment by azriel91** [comment]
bors try

File: amethyst_tiles/Cargo.toml (hunk 2 above)
Comment (mrhatman) [reply amethyst_tiles/Cargo.toml]: I just copied it from another place in the code. I can go through and update all of them if that makes sense for this PR

File: amethyst_tiles/src/error.rs (hunk 1 above)
Comment (mrhatman) [reply amethyst_tiles/src/error.rs]: I agree this looks weird. I was copying it from the previous panic message.

I will update this to be consistantly formatted.

File: amethyst_tiles/Cargo.toml (hunk 2 above)
Comment (azriel91) [reply amethyst_tiles/Cargo.toml]: ah don't worry about that, normally I'd do version bumps in a separate PR

File: amethyst_tiles/src/map.rs (hunk 3 above)
Comment (mrhatman) [reply amethyst_tiles/src/map.rs]: The reason they are unsigned is because the tile coordinates you clicked could be negative. This should be passed in the error.

Comment (azriel91) [reply amethyst_tiles/src/map.rs]: oh yes. Does it make sense to pass in whatever type `inverse` is?
Points I'm thinking of:
* is it clear enough for users to understand what the error is, using the raw type?
* it removes the possibility of `i32` overflow

Comment (mrhatman) [reply amethyst_tiles/src/map.rs]: Inverse is of type Point3<f32> I believe.

I believe because of the round and floor commands that making it an int is better 

Considering f32 can only store integers accurately up to about 2^23 I wouldn't worry about overflow. 

Changing this to allow for more precision would require fixes outside of the scope of this PR.

File: amethyst_tiles/src/error.rs (hunk 1 above)
Comment (mrhatman) [reply amethyst_tiles/src/error.rs]: Fixed
