### PR TITLE
Associate event reader with connection in network server example

### LINKED ISSUE #1760: [BUG] Network ReaderId invalidates after disconnection
## Description

I'm trying to use network and found in examples if client connects to the server after disconnection the server fails with panic.

## Reproduction Steps

1. Build `net_client` and `net_server` examples.
2. Launch `net_server`
3. Launch `net_client` for short period and stop it.
4. Watch `net_server` console until it says "Client Disconnects"
5. Launch `net_client` for short period and stop it again.
6. Panic happened.

## What You Expected to Happen

The server handles second client connection.

## What Actually Happened

The server uses `ReaderId` from previous connection which can not read data from new connection.

## Screenshots and Logs

Server log and backtrace
```
[INFO][net_server] CL: frame:95,abs_time:0.659644584,c:3
[INFO][net_server] CL: frame:95,abs_time:0.659644584,c:4
[INFO][net_server] CL: frame:95,abs_time:0.659644584,c:5
[INFO][net_server] CL: frame:95,abs_time:0.659644584,c:6
Client Disconnects
Received 2081 messages this frame connections: 1
Received 0 messages this frame connections: 0
Received 0 messages this frame connections: 0
Received 0 messages this frame connections: 0
Received 0 messages this frame connections: 0
Received 0 messages this frame connections: 0
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `InstanceId { inner: 0, msg: "`ReaderId` was not allocated by this `EventChannel`" }`,
 right: `Reference { inner: 0 }`: `ReaderId` was not allocated by this `EventChannel`', /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/shrev-1.1.1/src/util.rs:40:9
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: std::panicking::begin_panic_fmt
   6: shrev::util::InstanceId::assert_eq
             at ./<::std::macros::panic macros>:9
   7: shrev::storage::RingBuffer<T>::read
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/shrev-1.1.1/src/storage.rs:475
   8: shrev::EventChannel<E>::read
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/shrev-1.1.1/src/lib.rs:182
   9: amethyst_network::connection::NetConnection<E>::received_events
             at ./amethyst_network/src/connection.rs:107
  10: <net_server::SpamReceiveSystem as shred::system::System>::run
             at examples/net_server/main.rs:62
  11: <T as shred::system::RunNow>::run_now
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/system.rs:133
  12: shred::dispatch::stage::Stage::execute::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/dispatch/stage.rs:104
  13: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/for_each.rs:55
  14: <core::slice::IterMut<T> as core::iter::traits::iterator::Iterator>::fold
             at /tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libcore/slice/mod.rs:3178
  15: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/for_each.rs:55
  16: rayon::iter::plumbing::Producer::fold_with
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/plumbing/mod.rs:110
  17: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/plumbing/mod.rs:438
  18: rayon::iter::plumbing::bridge_producer_consumer
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/plumbing/mod.rs:397
  19: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/plumbing/mod.rs:373
  20: <rayon::slice::IterMut<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/slice/mod.rs:708
  21: rayon::iter::plumbing::bridge
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/plumbing/mod.rs:357
  22: <rayon::slice::IterMut<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/slice/mod.rs:684
  23: rayon::iter::for_each::for_each
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/for_each.rs:12
  24: rayon::iter::ParallelIterator::for_each
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/mod.rs:349
  25: shred::dispatch::stage::Stage::execute
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/dispatch/stage.rs:102
  26: shred::dispatch::dispatcher::Dispatcher::dispatch_par::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/dispatch/dispatcher.rs:87
  27: rayon_core::thread_pool::ThreadPool::install::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/thread_pool/mod.rs:132
  28: rayon_core::registry::Registry::in_worker_cold::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:495
  29: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/job.rs:115
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libstd/panic.rs:309
  31: std::panicking::try::do_call
             at /tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libstd/panicking.rs:294
  32: __rust_maybe_catch_panic
  33: std::panicking::try
             at /tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libstd/panicking.rs:273
  34: std::panic::catch_unwind
             at /tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libstd/panic.rs:388
  35: rayon_core::unwind::halt_unwinding
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/unwind.rs:17
  36: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/job.rs:115
  37: rayon_core::job::JobRef::execute
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/job.rs:59
  38: rayon_core::registry::WorkerThread::execute
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:734
  39: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:718
  40: rayon_core::registry::WorkerThread::wait_until
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:692
  41: rayon_core::registry::main_loop
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:812
  42: rayon_core::registry::ThreadBuilder::run
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:58
  43: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:103
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Your Environment

1. Operating System: Gentoo Linux AMD64
2. Operating System Version: 17.1
3. Version of Amethyst: master  58c1053c5d703ab8598b8bd6b0607802823c9193

### PR DESCRIPTION
**Pull request by o01eg**
## Description

Fixes #1760

## Modifications

- Allows the server from example to accept more than one connections.

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Ran `cargo test --all` locally if this modified any rs files.
- [x] Ran `cargo +stable fmt --all` locally if this modified any rs files.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

### CODE REVIEW

File: examples/net_server/main.rs [hunk 1]
```diff
@@ -35,31 +35,53 @@ impl SimpleState for State1 {
...
+    );
+    fn run(&mut self, (mut connections, mut readers, entities): Self::SystemData) {
         let mut count = 0;
         let mut connection_count = 0;
 
         for (e, connection) in (&entities, &mut connections).join() {
-            if self.reader.is_none() {
-                self.reader = Some(connection.register_reader());
-            }
+            let spam_reader = readers.get_mut(e);
```
Comment (torkleyy) [inline examples/net_server/main.rs]: This could make use of the Entry API.

Comment (o01eg) [reply examples/net_server/main.rs]: Thanks. I didn't find it myself. Fixed it.
