### PR TITLE
Fixed single frame animation

### LINKED ISSUE #781: Single frame animation breaks animation state
Something breaks on starting single frame animations. Not sure what, but the state after ending the animation is broken somehow, probably due to an incorrect `RestState` being created somewhere.

### PR DESCRIPTION
**Pull request by mh84**
Fixes #781

### CODE REVIEW

**Comment by mh84** [comment]
Everyone knows these bugs where u have to do hours of debugging to find them and change a single line of code to fix them ;)

File: examples/gltf/main.rs [hunk 1]
```diff
@@ -206,9 +206,6 @@ fn toggle_or_cycle_animation(
                 );
             }
             scene.animation_index += 1;
-            if scene.animation_index == 6 {
-                scene.animation_index = 7;
-            }
```
Comment (jojolepro) [inline examples/gltf/main.rs]: Why did you remove that one?

Comment (mh84) [reply examples/gltf/main.rs]: I guess animation 6 was skipped because it was broken as single frame animation, so we didnt skip it anymore because its fixed.

Comment (jojolepro) [reply examples/gltf/main.rs]: :+1:

File: docs/CHANGELOG.md [hunk 2]
```diff
@@ -67,6 +67,7 @@ The format is based on [Keep a Changelog][kc], and this project adheres to
 * `LMenu` and `RMenu` key codes, following the `winit` update. ([#906])
 
 ### Fixed
+* Fixed single frame animation ([#781])
```
Comment (jojolepro) [inline docs/CHANGELOG.md]: You also need to add a link to the pull request
```[#781]: https:......```

**Comment by jojolepro** [comment]
bors r+
thanks!
